name: Test PyPI Build

on: [workflow_dispatch]

jobs:

  # ##############################################################################

  # cibuildwheel==3.x.x doesn't work for Windows ARM64 + Python < 3.11

  # ##############################################################################

  # build_windows_intel:
  #   name: Build windows-intel wheels
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python 3.x
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.x'
  #     - name: Install cibuildwheel
  #       run: python -m pip install cibuildwheel==3.1.4
  #     - name: Build wheels
  #       run: python -m cibuildwheel --output-dir wheelhouse
  #       env:
  #         CIBW_BUILD_VERBOSITY: 1
  #         CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
  #         CIBW_SKIP: "*-win32 pp*"
  #         CIBW_ARCHS_WINDOWS: "AMD64"
  #     - name: Archive wheels
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: windows-intel-wheels
  #         path: ./wheelhouse/*.whl

  # build_windows_arm:
  #   name: Build windows-arm wheels
  #   runs-on: windows-11-arm
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python 3.x
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.x'
  #     - name: Install cibuildwheel
  #       run: python -m pip install cibuildwheel==3.1.4
  #     - name: Build wheels
  #       run: python -m cibuildwheel --output-dir wheelhouse
  #       env:
  #         CIBW_BUILD_VERBOSITY: 1
  #         CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
  #         CIBW_SKIP: "pp*"
  #         CIBW_ARCHS_WINDOWS: "ARM64"
  #     - name: Archive wheels
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: windows-arm-wheels
  #         path: ./wheelhouse/*.whl

  # build_windows_all_p37:
  #   name: Build windows wheels (Python 3.7)
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Set up Python 3.x
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.x'
  #     - name: Install cibuildwheel
  #       run: python -m pip install cibuildwheel==2.23.3
  #     - name: Build wheels
  #       run: python -m cibuildwheel --output-dir wheelhouse
  #       env:
  #         CIBW_BUILD_VERBOSITY: 1
  #         CIBW_BUILD: "cp37-*"
  #         CIBW_SKIP: "*-win32 pp*"
  #         CIBW_ARCHS_WINDOWS: "AMD64 ARM64"
  #     - name: Archive wheels
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: windows-all-p37-wheels
  #         path: ./wheelhouse/*.whl

  # ##############################################################################

  build_windows_all:
    name: Build windows wheels
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.3
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp37-* cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "*-win32 pp*"
          CIBW_ARCHS_WINDOWS: "AMD64 ARM64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: windows-all-wheels
          path: ./wheelhouse/*.whl

  build_macos_intel:
    name: Build macos-intel wheels
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.1.4
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "pp*"
          CIBW_ARCHS_MACOS: "x86_64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: macos-intel-wheels
          path: ./wheelhouse/*.whl

  build_macos_intel_p37:
    name: Build macos-intel wheels (Python 3.7)
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.3
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp37-*"
          CIBW_SKIP: "pp*"
          CIBW_ARCHS_MACOS: "x86_64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: macos-intel-p37-wheels
          path: ./wheelhouse/*.whl

  build_macos_arm:
    name: Build macos-arm wheels
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.1.4
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "pp*"
          CIBW_ARCHS_MACOS: "arm64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm-wheels
          path: ./wheelhouse/*.whl

  build_linux_intel:
    name: Build linux-intel wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.1.4
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "*-manylinux_i686 pp*"
          CIBW_ARCHS_LINUX: "x86_64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: linux-intel-wheels
          path: ./wheelhouse/*.whl

  build_linux_intel_p37:
    name: Build linux-intel wheels (Python 3.7)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.3
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp37-*"
          CIBW_SKIP: "*-manylinux_i686 pp*"
          CIBW_ARCHS_LINUX: "x86_64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: linux-intel-p37-wheels
          path: ./wheelhouse/*.whl

  build_linux_arm:
    name: Build linux-arm wheels
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.1.4
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "pp*"
          CIBW_ARCHS_LINUX: "aarch64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm-wheels
          path: ./wheelhouse/*.whl

  build_linux_arm_p37:
    name: Build linux-arm wheels (Python 3.7)
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.23.3
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp37-*"
          CIBW_SKIP: "pp*"
          CIBW_ARCHS_LINUX: "aarch64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm-p37-wheels
          path: ./wheelhouse/*.whl

  build_source:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          pip install "setuptools>=67.8.0"
          pip install wheel build
      - name: Build .tar.gz
        run: python -m build --sdist
      - name: Archive .tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: source-dist
          path: dist/*.tar.gz
